import { db, firebaseReady, auth } from "./firebase-config.js";
import { doc, getDoc, collection, addDoc, onSnapshot, serverTimestamp, query, where, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { addToCart, subscribeCart } from "./cart.js";
import { watchAuth } from "./auth.js";
const id = new URLSearchParams(location.search).get("id");
const fallback = { id, title: "Air Max Dn", brand: "Nike", price: 170, category: "running", sizes: ["40", "41", "42", "43", "44"], stock: { almaty: 7, astana: 5 }, images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85"], description: "A kinetic everyday runner with a responsive step." };
let product = fallback; let selectedSize = product.sizes[0];
const money = value => `$${Number(value).toFixed(0)}`;
function render() { document.querySelector("#product-content").innerHTML = `<div class="detail-gallery"><img src="${product.images?.[0]}" alt="${product.title}" onerror="this.style.display='none'"><div class="gallery-dots">${(product.images || [""]).map((_, index) => `<button class="active" aria-label="View image ${index + 1}"></button>`).join("")}</div></div><div class="detail-copy"><p class="eyebrow">${product.brand} / ${product.category}</p><h1>${product.title}</h1><p class="detail-price">${money(product.price)}</p><p class="detail-description">${product.description || "Designed for daily distance, wherever the day takes you."}</p><div class="size-header"><span>Select size</span><span class="muted">EU / true to size</span></div><div class="size-grid">${(product.sizes || []).map(size => `<button class="size-button ${size === selectedSize ? "active" : ""}" data-size="${size}">${size}</button>`).join("")}</div><button class="button button-dark add-button" id="add-button">Add to bag <span>↗</span></button><p class="stock-note">${product.stock > 0 ? `${product.stock} pairs available / live inventory` : "Currently sold out"}</p></div><section class="reviews"><div class="section-heading"><div><p class="eyebrow">COMMUNITY NOTES</p><h2>Reviews</h2></div></div><div id="review-list" class="review-list"><p class="muted">Loading notes...</p></div><form id="review-form" class="review-form"><input name="rating" type="number" min="1" max="5" placeholder="Rating 1-5" required><input name="text" placeholder="Share your take" required><button class="button button-dark">Post note</button></form></section>`; document.querySelectorAll(".size-button").forEach(button => button.addEventListener("click", () => { selectedSize = button.dataset.size; render(); })); document.querySelector("#add-button").addEventListener("click", async () => { await addToCart(product, selectedSize); const toast = document.querySelector("#toast"); toast.textContent = "Added to bag"; toast.classList.add("visible"); setTimeout(() => toast.classList.remove("visible"), 1800); }); document.querySelector("#review-form").addEventListener("submit", async event => { event.preventDefault(); if (!firebaseReady || !auth.currentUser) return alert("Sign in to leave a review."); const data = Object.fromEntries(new FormData(event.currentTarget)); await addDoc(collection(db, "reviews"), { productId: product.id, userId: auth.currentUser.uid, displayName: auth.currentUser.displayName || "Member", rating: Number(data.rating), text: data.text, createdAt: serverTimestamp() }); event.currentTarget.reset(); }); loadReviews(); }
function loadReviews() { if (!firebaseReady || !product.id) return; onSnapshot(query(collection(db, "reviews"), where("productId", "==", product.id), orderBy("createdAt", "desc")), snapshot => { const list = document.querySelector("#review-list"); if (!list) return; list.innerHTML = snapshot.empty ? `<p class="muted">Be the first to leave a note.</p>` : snapshot.docs.map(item => `<article class="review-row"><strong>${"★".repeat(item.data().rating)}</strong><p>${item.data().text}</p><span>${item.data().displayName}</span></article>`).join(""); }); }
async function init() { if (firebaseReady && id) { const snapshot = await getDoc(doc(db, "products", id)); if (snapshot.exists()) product = { id: snapshot.id, ...snapshot.data() }; } render(); }
subscribeCart();
init();